
LOCATE_BY_XPATH = "XPATH"
LOCATE_BY_ID = "ID"
LOCATE_BY_CLASS_NAME = "CLASS_NAME"
LOCATE_BY_CSS_SELECTOR = "CSS_SELECTOR"
LOCATE_BY_LINK_TEXT = "LINK_TEXT"
LOCATE_BY_PARTIAL_LINK_TEXT = "PARTIAL_LINK_TEXT"
LOCATE_BY_TAG_NAME = "TAG_NAME"
